idf_component_register(
    SRCS
        manager/tasks.c
        registry/task_registry.c
    INCLUDE_DIRS
        "include"
    REQUIRES
        alert_manager
        cjson
        config_storage
        dht
        freebox_report
        jeedom
        led_ctrl
        prediction_engine
        serial_manager
        sht31
        thermal_engine
        thermostat
        time_utils
        weather
        weather_store
        wifi
)
